### ISSUE TITLE
Create a Github Actions pipeline for Helm Chart

### ISSUE THREAD

**Issue by ChrisJBurns** [vinzscam/backstage-chart#21]
Currently, we do not have a Github Actions pipeline to test changes proposed in a PR.

I propose the following:
- Add a GitHub Actions pipeline to test changes against PR's (run helm lint tests and validate charts, it will also fail if it does not detect a version bump (ready for the master release)

I can do this, should be relatively easy. I have already done this with a Helm Chart I created for the [Pact Broker](https://github.com/ChrisJBurns/pact-broker-chart/tree/master/.github/workflows).

Let me know what you guys think: @vinzscam  @cmoulliard

**Comment by cmoulliard** [comment]
I'm 100% in favour of having such github actions able to check the content of the helm chart, to perform a end-to-end test on kind cluster, etc

**Comment by ChrisJBurns** [comment]
Closing as this has repo has been deprecated in favour of https://github.com/backstage/charts
