### ISSUE TITLE
INSTALLATION FAILED: The repository name of the image is required (e.g. my-backstage:tag | docker.io/my-backstage:tag)

### ISSUE THREAD

**Issue by xerere** [vinzscam/backstage-chart#25]
After successfully issuing 
`helm repo add backstage https://vinzscam.github.io/backstage-chart`
the next suggested command for install: 
`helm install my-backstage-release backstage/backstage`
results in 
`Error: INSTALLATION FAILED: execution error at (backstage/templates/backstage-deployment.yaml:1:61): The repository name of the image is required (e.g. my-backstage:tag | docker.io/my-backstage:tag)`

**Comment by ChrisJBurns** [comment]
@xerere  Are you ok with us closing this, given @vinzscam response?
