### ISSUE TITLE
[enhancement] Implementation of Dedicated Backstage Service Account

### ISSUE THREAD

**Issue by ChrisJBurns** [vinzscam/backstage-chart#9]
Shall we add a dedicated service account for backstage by default, instead of using the default one? This could open up the door on future enhancements and tightening of security controls using Kubernetes RBAC as well as being able to attach pull secrets to the SA instead of passing them to the deployment.

**Comment by ChrisJBurns** [comment]
Nope not yet @cmoulliard I was waiting to see if there was an interest first

**Comment by ChrisJBurns** [comment]
@vinzscam  What do you think about this? If you're all for it, I can raise a simple PR to add an SA, just to get the ball rolling

**Comment by vinzscam** [comment]
> @vinzscam What do you think about this? If you're all for it, I can raise a simple PR to add an SA, just to get the ball rolling

sure it looks like a good addition 😄

**Comment by vinzscam** [comment]
Closed by #22
